### ISSUE TITLE
Error with bundle serve

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#192]
Hi - I am seeing the following error when I run bundle serve. 
`jekyll 3.9.0 | Error:  No such file or directory @ realpath_rec - /somepath/ESMValTool_Tutorial/_episodes/ranjinis@host596.jc.rl.ac.uk.20029:1614676771
`
Not sure if it has to do with JASMIN upgrades. Any thoughts?

**Comment by SarahAlidoost** [comment]
@rswamina Looking at the error, it seems that the problem is related to the working directory. Can you please check if you are in the directory `ESMValTool_Tutorial` and not the sub-directory `_episodes` when you run bundle serve. 

Also, I am wondering why you don't use the command `make serve` instead of `bundle serve`.

**Comment by rswamina** [comment]
I can confirm that I am in the ESMValTool_Tutorial directory. For some reason running `make serve` does not find `bundle` for me. I think it has something to do with a new shell being created. I haven't been able to debug that for a while, so resorted to the command line execution of the `bundle serve` command.

**Comment by SarahAlidoost** [comment]
Thank you Ranjini. Unfortunately, it is difficult to debug this issue because I cannot reproduce the error and don't have access to JASMIN. Also, I couldn't find an online guide to address this issue. I am not sure if you are using the tutorial conda environment. One thing that I would try is to delete the conda environment and re-create it. Also, I suggest asking other esmvaltool developers who have access to JASMIN.

**Comment by rswamina** [comment]
I tried updating the conda env but can try to delete and start afresh. If that doesn't work, I will get someone with access to JASMIN to try it. Will keep this thread updated.

**Comment by rswamina** [comment]
and thanks!

**Comment by rswamina** [comment]
@SarahAlidoost - I removed and reinstalled the conda env and it seems to work now. Will post here if there are further problems. I will check that  I am able to successfully push code etc. and then close the issue.

**Comment by rswamina** [comment]
Everything works fine so I will close this issue now. Thanks @SarahAlidoost !
