### ISSUE TITLE
cloning an "external" public repo does not require GitHub username and a personal token as password

### ISSUE THREAD

**Issue by annefou** [ESMValGroup/ESMValTool_Tutorial#201]
In episode 7 "[Contribution and development](https://esmvalgroup.github.io/ESMValTool_Tutorial/07-development-setup/index.html
)":

_This command will ask your GitHub username and a personal token as password. Please follow instructions on GitHub token authentication requirements to create a personal access token._ 

I would rather have this as a "note/remark" because it does not necessarily apply (I am not a collaborator of ESMValTool_Tutorial repo so I do not need it).

**Comment by SarahAlidoost** [comment]
Thanks for creating the issue. Episode 7 illustrates guidelines on how to contribute to ESMValtool development rather than the tutorial, it is mentioned at the top of the episode: 
`ESMValTool is an open-source project in ESMValGroup. We can contribute to its development by:`

Also, token authentication is a new requirement by GitHub for developers. We have already provided a link to the GitHub instructions in this episode, see:
_This command will ask your GitHub username and a personal **token** as password. Please follow instructions on [GitHub token authentication requirements](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/#what-you-need-to-do-today) to create a personal access token._ 

Hope that this explanation addresses the issue.

**Comment by rswamina** [comment]
Dear @annefou - If you are happy with @SarahAlidoost 's response, can we close this issue? If not, let us know if you ahev concerns.
