### ISSUE TITLE
404 error when accessing the ESMValTool Tutorial

### ISSUE THREAD

**Issue by ehogan** [ESMValGroup/ESMValTool_Tutorial#244]
Hi @ESMValGroup/userengagementteam 

When I follow https://esmvalgroup.github.io/ESMValTool_Tutorial I get taken to a page that says:

```
Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the [webmaster](mailto:webmaster-pa@dlr.de).
Error 404
[www.esmvaltool.org](https://www.esmvaltool.org/)
Apache
```

Does the link above work for others? Is it just me?

**Comment by rswamina** [comment]
> Hi @ESMValGroup/userengagementteam
> 
> When I follow https://esmvalgroup.github.io/ESMValTool_Tutorial I get taken to a page that says:
> 
> ```
> Object not found!
> 
> The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.
> 
> If you think this is a server error, please contact the [webmaster](mailto:webmaster-pa@dlr.de).
> Error 404
> [www.esmvaltool.org](https://www.esmvaltool.org/)
> Apache
> ```
> 
> Does the link above work for others? Is it just me?

@remi-kazeroni - Is this something that can be fixed by you? The webmaster address is a DLR address. I wonder if it is due to our website migration process but perhaps not.

**Comment by remi-kazeroni** [comment]
Indeed, this problem is related to the website migration. We missed the fact that the tutorial uses the same domain (esmvalgroup.github.io) as the new website, sorry for that! We have temporary changed the website settings so that the tutorial is now available again.

To finish the website migration, we need to talk to our IT admins at DLR and ask them to help us link the github based website to esmvaltool.org, not sure how long this will take. This is likely to impact the tutorial again. It would be good to discuss now if we would want to keep the current address for the tutorial (https://www.esmvaltool.org/ESMValTool_Tutorial) or have it as a subdomain of esmvaltool.org (i.e. esmvaltool.org/tutorial or tutorial.esmvaltool.org). The latter would be similar to our docs (docs.esmvaltool.org). I'll open a separate issue to discuss about that.
