### ISSUE TITLE
Fix path to diagnostic in the Running the episode 04-recipe 

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#74]
I believe the full path to the diagnostic must be given if we run the tool with the conda installation so that should be amended in the text and/or the recipe as needed.

**Comment by bouweandela** [comment]
I have added some explanation about this in #97. If the ESMValTool is installed and a relative path is given to the diagnostic, it will first try to use the installed version of the diagnostic script, so this works fine in recipe_example.yml, because the script in the example recipe is installed along with the ESMValTool.
